# Plot footprint and trajs from aircraft receptors
# Jan. 29th, 2025 by John C. Lin (John.Lin@utah.edu)

#########################
outputdir <- paste0("out/by-id/")
pngfileTF <- FALSE; overwritepngfileTF <- TRUE
GoogleMapTF <- TRUE
plotflttrackTF <- TRUE  # add flight track from that flight?
flttrackdatdir <- "/uufs/chpc.utah.edu/common/home/u0791084/PROJECTS/USOS/USOS_Aircraft/USOS_Aircraft_Data/"
USOS.receptors <- readRDS("~/PROJECTS/USOS/USOS_Aircraft/USOS_selected_receptors.rds")   # generated by 'determine_aircraft_receptors.r'

#lat/lon range of USOS aircraft receptors
XLIMS <- c(-114.5,-108.6);YLIMS <- c(39,42)

#range of footprint plot (log10 limits)
ZLIMS<-c(-7,-1)
#########################

require(fields);require(ncdf4)
require(maps);require(RgoogleMaps)

#loop over the YYYYMMDD folders
filelabels <- list.files(outputdir,pattern="20240730")
filelabels <- rev(filelabels)
filelabels <- sample(filelabels,min(c(5,length(filelabels))))  #randomly sample a few to plot
# filelabels is in format of "202408051746_-112.39181332_41.08104761_1929"
for(i in 1:length(filelabels)){
  ncfilenm<-paste0(outputdir,"/",filelabels[i],"/",filelabels[i],"_foot.nc")
  if(!file.exists(ncfilenm)){print(paste("no footprint output for:",filelabels[i]));next}

  #Generate footprint
  footfile<-nc_open(ncfilenm)
  lat<-ncvar_get(footfile,"lat");lon<-ncvar_get(footfile,"lon")
  foot.all<-ncvar_get(footfile,"foot")
  #sel.y<-lat>YLIMS[1]&lat<YLIMS[2];flat<-lat[sel.y]
  #sel.x<-lon>XLIMS[1]&lon<XLIMS[2];flon<-lon[sel.x]
  flat<-lat;flon<-lon
  footsum<-apply(foot.all,c(1,2),sum)   #sum over backward time
  #footsum<-footsum[sel.x,sel.y]
  foot.log<-log10(footsum);foot.log[footsum==0]<-NA

  #Read in trajectories 
  trajfile<-paste0(outputdir,"/",filelabels[i],"/",filelabels[i],"_traj.rds")
  if(!file.exists(trajfile)){print(paste("cannot find trajectory file",trajfile));next}
  dat.all<-readRDS(file=trajfile)
  receptor<-dat.all$receptor
  lon0<-receptor$long;lat0<-receptor$lati;agl0<-receptor$zagl
  receptor$run_time<-strftime(receptor$run_time,"%Y-%m-%d %H:%M",tz="UTC")
  dat<-dat.all$particle

  #Plot track from that flight
  if(plotflttrackTF){
    tmp <- strsplit(filelabels[i],"_")[[1]]
    YYYYMMDDHHMMss <- tmp[1]; Latitude <- as.numeric(tmp[3]);  Longitude <- as.numeric(tmp[2]);  ALTAGL <- as.numeric(tmp[4])
    sel <- USOS.receptors$Latitude==Latitude & USOS.receptors$Longitude==Longitude & USOS.receptors$ALTAGL==ALTAGL 
    if(sum(sel)!=1)stop(paste("not unique fltlabel:",filelabels[i]))
    fltcode <- USOS.receptors$fltlabel[sel]
    fltdat <- readRDS(paste0(flttrackdatdir,"/",fltcode,".rds"))
    # just plot 1/100th of flttrack
    inds <- seq(1,nrow(fltdat),10)
    fltdat <- fltdat[inds,]
  } # if(plotflttrackTF){

  #Check whether PNG file exists or not
  if(pngfileTF){
    #pngfile <- paste0(outputdir,"/",filelabels[i],"/",filelabels[i],".png")
    pngfile <- paste0(filelabels[i],".png")
    if(!overwritepngfileTF){if(file.exists(pngfile)){print(paste("PNG file already exists!; skip:",pngfile));next}}
  } #if(pngfileTF){

  lats<-dat$lati;lons<-dat$long
  #sel<-lats>YLIMS[1]&lats<YLIMS[2]
  #sel<-sel&(lons>XLIMS[1]&lons<XLIMS[2])
  #lats<-lats[sel];lons<-lons[sel]
if(!GoogleMapTF){
  dev.new();par(cex.axis=1.3,cex.lab=1.3,cex.main=1.1)
  image.plot(flon,flat,foot.log)
  #add trajectories
  points(lons,lats,pch=16,col="darkgray",cex=0.2)
  #add flt track
  if(plotflttrackTF)points(fltdat$Longitude,fltdat$Latitude,pch=16,col="black",cex=0.3)
  #add receptor location
  points(lon0,lat0,pch=17,col="red",cex=2.0)
  map("state",add=TRUE)  #;map("world",add=TRUE)
  map.cities(minpop=100000,cex=1.2)
  title(main=paste("USOS Aircraft Footprint (STILT model) at receptor (red triangle):\n",receptor$run_time,"UTC   ",
                     round(lon0,digits=3),"LON ",round(lat0,digits=3),"LAT ",round(agl0,digits=3),"m-AGL"),cex.main=1.1)
}else{
  #map defined by "zoom level"
  #  center<-c(mean(lats,na.rm=T),mean(lons,na.rm=T))
  #  center[1]<-center[1]-0.3;center[2]<-center[2]+0.2
  #  MyMap <- GetMap(center,zoom=9,maptype="terrain",frame=TRUE,GRAYSCALE=FALSE)
  #map defined by bounding box
  #bb <- qbbox(lat=lats, lon=lons)   #use trajectories to define map
  #bb <- qbbox(lat=flat, lon=flon)    #use footprint to define map
  bb <- qbbox(lat=YLIMS, lon=XLIMS)    #use footprint to define map
  MyMap <- GetMap.bbox(bb$lonR, bb$latR, maptype="terrain", frame=TRUE,GRAYSCALE=FALSE)
  PlotOnStaticMap(MyMap,mar=c(2,1,3,1))

  #Add trajectories
  #site.xy<- LatLon2XY.centered(MyMap, lat=as.numeric(dat$lati), lon=as.numeric(dat$long))
  site.xy<- LatLon2XY.centered(MyMap, lat=as.numeric(lats), lon=as.numeric(lons))
  points(site.xy$newX,site.xy$newY,pch=16,col="darkgray",cex=0.2)
  #add flt track
  if(plotflttrackTF){
    site.xy<- LatLon2XY.centered(MyMap, lat=as.numeric(fltdat$Latitude), lon=as.numeric(fltdat$Longitude))
    points(site.xy$newX,site.xy$newY,pch=16,col="black",cex=0.3)
  } # if(plotflttrackTF){

  #Add receptor location
  site.xy<- LatLon2XY.centered(MyMap, lat=as.numeric(lat0), lon=as.numeric(lon0))
  points(site.xy$newX,site.xy$newY,pch=17,col="red",cex=1.5)

  title(main=paste("USOS Aircraft Footprint (STILT model) at receptor (red triangle):\n",receptor$run_time,"UTC   ",
                     round(lon0,digits=3),"LON ",round(lat0,digits=3),"LAT ",round(agl0,digits=3),"m-AGL"),cex.main=1.1)

  #Add footprint
  alpha<-0.45  #transparency
  lats.m<-matrix(rep(flat,length(flon)),byrow=T,ncol=length(flat))
  lons.m<-matrix(rep(flon,length(flat)),ncol=length(flat))
  xys<- LatLon2XY.centered(MyMap, lat=as.vector(lats.m), lon=as.vector(lons.m)) #converting lat/lon coordinates to map coordinates
  image.coords.x<-matrix(xys$newX,ncol=length(flat))
  image.coords.y<-matrix(xys$newY,ncol=length(flat))
  COLS<-c("white","darkgray","lightblue","RoyalBlue","darkgreen","yellow","orange","red") #colorscale
  colsc<-designer.colors(n=64,alpha=alpha,col=COLS)
  colsc.legend<-designer.colors(n=64,alpha=1.0,col=COLS)

  #generate image
  image(x=image.coords.x[,1],y=image.coords.y[1,],z=foot.log,
          col=colsc,ylim=c(MyMap$BBOX$ll[1],MyMap$BBOX$ur[1]),xlim=c(MyMap$BBOX$ll[2],MyMap$BBOX$ur[2]),add=T,zlim=ZLIMS)

  #Add legend 
  image.plot(x=image.coords.x[,1],y=image.coords.y[1,],z=foot.log,
        col=colsc.legend,ylim=c(MyMap$BBOX$ll[1],MyMap$BBOX$ur[1]),xlim=c(MyMap$BBOX$ll[2],MyMap$BBOX$ur[2]),add=T,
       legend.lab="log10(footprint)",legend.line=2,zlim=ZLIMS,legend.only=T,horizontal=T,legend.width=0.8)
} #if(!GoogleMapTF){

  if(pngfileTF){
    dev.copy(png,filename=pngfile);dev.off()
    print(paste(pngfile,"produced"))
  } #if(pngfileTF){
  nc_close(footfile)
  gc()
} #for(i in 1:length(filelabels)){


